/*
 * pki.in GO
 *
 * pki in API docs
 *
 * API version: 1.0.0
 * Contact: paul.goehring@student.uni-tuebingen.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// public key information of client
type Jwk struct {

	Kty string `json:"kty"`

	Use string `json:"use,omitempty"`

	Alg string `json:"alg,omitempty"`

	N string `json:"n"`

	E string `json:"e"`

	Kid string `json:"kid,omitempty"`
}
