/*
 * pki.in GO
 *
 * pki in API docs
 *
 * API version: 1.0.0
 * Contact: paul.goehring@student.uni-tuebingen.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	root "rpki/go"
)

func main() {
	log.Printf("Server started")

	log.Printf("Init Root Server")

	root.Initialize()
	server := http.Server{
		Addr:      ":8090",
		TLSConfig: root.DefineTLSConfig(),
	}
	server2 := http.Server{
		Addr: ":8091",
	}

	// https setup for well-known/certs endpoint
	mux := http.NewServeMux()
	mux.HandleFunc("/.well-known/certs", root.WellKnownCertsGet)

	server3 := http.Server{
		Addr:    ":8444",
		Handler: mux,
	}

	router := root.NewRouter()
	router2 := root.NewRouter2()
	server.Handler = router
	server2.Handler = router2

	go func() {
		log.Fatal(server.ListenAndServeTLS("", ""))
	}()
	go func() {
		log.Fatal(server3.ListenAndServeTLS(root.PathOwnCrt, root.PathServerKey))
	}()
	log.Fatal(server2.ListenAndServe())
}
