/*
 * pki.in GO
 *
 * pki in API docs
 *
 * API version: 1.0.0
 * Contact: paul.goehring@student.uni-tuebingen.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	root "rpki/go"
)

func main() {
	log.Printf("Server started")

	log.Printf("Init Root Server")

	root.Initialize()

	router := root.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
